# Copyright 2021 The Periph Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# See https://github.com/periph/gohci
version: 1
workers:
- checks:
  - cmd:
    - go
    - test
    - ./...
  # Test in advance: host
  - dir: ..
    cmd:
    - git
    - clone
    - --depth
    - 1
    - https://github.com/periph/host
  - dir: ../host
    cmd:
    - go
    - mod
    - edit
    - -replace=periph.io/x/d2xx=../d2xx
  - dir: ../host
    cmd:
    - go
    - get
    - -t
    - ./...
  - dir: ../host
    cmd:
    - go
    - test
    - -short
    - ./...
  # Test in advance: cmd
  - dir: ..
    cmd:
    - git
    - clone
    - --depth
    - 1
    - https://github.com/periph/cmd
  - dir: ../cmd
    cmd:
    - go
    - mod
    - edit
    - -replace=periph.io/x/d2xx=../d2xx
  - dir: ../cmd
    cmd:
    - go
    - get
    - -t
    - ./...
  - dir: ../cmd
    cmd:
    - go
    - test
    - -short
    - ./...
